### ISSUE TITLE
Does not work with kicad-nightly

### ISSUE THREAD

**Issue by bullestock** [AislerHQ/PushForKiCad#25]
I am using KiCAD Version: 7.99.0-2672-g8aa408f0c9 with AISLER-Push version 0.1.9.

Trying to push produces this backtrace in the console:

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/torsten/.local/share/kicad/7.99/3rdparty/plugins/com_github_aislerhq_PushForKiCad/push_thread.py", line 126, in run
    'mpn': self.getMpnFromFootprint(f),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/torsten/.local/share/kicad/7.99/3rdparty/plugins/com_github_aislerhq_PushForKiCad/push_thread.py", line 175, in getMpnFromFootprint
    if f.HasProperty(key):
       ^^^^^^^^^^^^^
AttributeError: 'FOOTPRINT' object has no attribute 'HasProperty'
```

**Comment by tbolender** [comment]
Unfortunately, it is hard to support Kicad nightly as interfaces to prepare the production data for might change. We will therefore not support the nightly version. As alternative, you are welcome to upload the project as ODB++ when using nightly builds.
